ex12_html-css-js
Indigoinspn/external-courses pull request #16
Opened 2019-05-03 18:08 UTC by Indigoinspn

task-01.html  - Adaptive article block.
task-02.html  - Dropdown menu through JS only.

2019-05-04 09:58 UTC, eugrdn requested changes

2019-05-04 09:58 UTC, eugrdn commented on src/ex12_html-css-js/task-02.html
> +                return;
здесь проще использовать else

2019-05-04 09:58 UTC, eugrdn commented on src/ex12_html-css-js/task-02.html
> +        function menuShowOrHide() {
show or hide обычно называют `toggle`

2019-05-04 09:58 UTC, eugrdn commented on src/ex12_html-css-js/task-02.html
> +            if (!container.contains(aTag)) return;
можно объединить с предыдущим условием, раз результат одинаковый и в onmouseout тоже

2019-05-04 09:58 UTC, eugrdn commented on src/ex12_html-css-js/task-02.html
> +        <div id="container">
более семантично было бы сделать через ul/li, но не обязательно

2019-05-04 09:58 UTC, eugrdn commented on src/ex12_html-css-js/task-02.html
> +    <nav id="dropdown-menu" class="">
пустой класс и ниже тоже

2019-05-08 08:03 UTC, Indigoinspn commented on src/ex12_html-css-js/task-02.html
> +                return;
Поправила

2019-05-08 08:03 UTC, Indigoinspn commented on src/ex12_html-css-js/task-02.html
> +        function menuShowOrHide() {
Поправила

2019-05-08 08:03 UTC, Indigoinspn commented on src/ex12_html-css-js/task-02.html
> +            if (!container.contains(aTag)) return;
объединила

2019-05-08 08:05 UTC, Indigoinspn commented on src/ex12_html-css-js/task-02.html
> +        <div id="container">
Поняла)

2019-05-08 08:05 UTC, Indigoinspn commented on src/ex12_html-css-js/task-02.html
> +    <nav id="dropdown-menu" class="">
убрала

2019-05-09 14:41 UTC, merged