ex13_library : Online book store page.
Indigoinspn/external-courses pull request #17
Opened 2019-05-05 20:10 UTC by Indigoinspn

Created base landing page according to given design.
Book information (Image/Title/Author/Star rating) rendered through JS.

2019-05-09 16:26 UTC, eugrdn requested changes
по верстке:
- нужно всю библиотеку обернуть в контейнер и вытянуть ее на 100% ширины
- прижать футер к низу страницы

можно так же в этой же ветке постараться сделать обработчики для рейтинга (сейчас + за половинчатые, но возможно будет сложно именно при обработке событий, тогда можешь оставить только полное заполнение)

2019-05-09 16:26 UTC, eugrdn commented on src/ex13_library/main.js
> +function toPublishBooks(arr){
зачем `to`? 🤔

2019-05-09 16:26 UTC, eugrdn commented on src/ex13_library/main.js
> +    for (var i=0; i< arr.length; i++) {
зачем все усложнять, если можно воспольоваться уже готовым методом `forEach`? 🙂

2019-05-09 16:26 UTC, eugrdn commented on src/ex13_library/main.js
> +    for (var i=0; i< arr.length; i++) {
и все, что ниже, для каждой книжки я бы вынес в отдельную функцию, возможно, в дальнейшем, пригодится ее использование где-то еще

2019-05-09 17:16 UTC, Indigoinspn commented on src/ex13_library/main.js
> +function toPublishBooks(arr){
Чтобы показать, что функция выполняет действие) ( "публикует" книги на странице.

2019-05-09 17:52 UTC, eugrdn commented on src/ex13_library/main.js
> +function toPublishBooks(arr){
обычно в названиях методов/функций не используют артикли, предлоги, частицы, не только в js, но и в других языках, по крайней мере я не встечал, возможно, чтобы не добавлять к и так непростой логике еще и грамматику 🙂 
лучше просто `publishBooks`, а еще лучше `renderBooks`

2019-05-10 05:23 UTC, Indigoinspn commented on src/ex13_library/main.js
> +function toPublishBooks(arr){
хорошо=)

2019-05-10 18:01 UTC, Indigoinspn commented on src/ex13_library/main.js
> +    for (var i=0; i< arr.length; i++) {
Заменила на forEach метод и вынесла в отдельную функцию.

2019-05-10 18:02 UTC, Indigoinspn commented on src/ex13_library/main.js
> +function toPublishBooks(arr){
Поправила название

2019-05-10 18:04 UTC, Indigoinspn commented
Прижала футер к низу страницы и растянула контент на всю ширину.

2019-05-15 19:42 UTC, eugrdn requested changes
Комментарии в коде бывают нужны, но лучше когда их нет, как минимум закоменнтированного кода 🙂

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +document.body.style.overflow = "hidden";
ой-ой
смысл такой: тебе объединить header, main и footer в один контейнер, указать у него высоту 100vh, ширину 100%, и дальше от этих размеров исходить отображая дочерние элементы, относительную высоту(можно в %), ширину (можно в %), отступы не задают

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +document.body.style.overflow = "hidden";
все это делается средствами html и css

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +dataBooks.forEach(renderBooks);
forEach, т.е для каждого элемента dataBooks, те не renderBooks, a renderBook

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +  var starRateContainer = booksContainer.getElementsByClassName("star-rating-container")[i];
а зачем тебе сначала добавлять книгу в dom, а потом тут же ее из него доставать, чтобы добавить рейтинг, если можно отрендерить сразу с ним??

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +  var wholeFilledStars = Math.round(Math.floor(starRate));
Math.round(Math.floor( )) вынести в отдельную функцию

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +  if (start === 0 & finish === 0) { // if bookRating 0 and initial filledStarIndex = selectedStarIndex = 0 (=index of fist star half)
здесь наверное `&&`?
не понял где в этом условии проверяется, что `bookRating 0`

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +  findIndexOfSelectedStar(target,bookIndex);
эта функция не просто ищет индекс, она делает еще кучу всего, а возвращаемое значение как раз не используется

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +  findIndexOfSelectedStar(target,bookIndex);
нужно либо вынести из нее часть, которая изменяет звезды, либо переименовать

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +var bookId,
от этих глобавльных переменных лучше избавится, использовать только внутри функций

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +  getBookRating (bookIndex); // get rating from dataBooks array and save to filledStarIndex
возвращаемое значение не используется

2019-05-15 19:42 UTC, eugrdn commented on src/ex13_library/main.js
> +  for (var k = 0; k < stars.length; k++) {
лучше привести к массиву и использовать forEach

2019-05-16 05:21 UTC, Indigoinspn commented on src/ex13_library/main.js
> +document.body.style.overflow = "hidden";
Я вообще думала, что ты имеешь в виду, чтобы сайт занимал всю страницу и не было прокрутки). Когда я применяла 100vh страница занимала весь экран браузера, но при прокрутке под футером появлялось пустое место.  Еще хотела уточнить на макете сайта края закруглены, если сайт занимает 100% ширины, то в углях появляются белые просветы.

2019-05-16 09:05 UTC, eugrdn commented on src/ex13_library/main.js
> +document.body.style.overflow = "hidden";
> Я вообще думала, что ты имеешь в виду, чтобы сайт занимал всю страницу и не было прокрутки
да, я это и имел в виду, но ты сейчас просто обрезаешь то, что в нее не влезло, так нехорошо
можно без закруглений, там видимо скрин с macbook

2019-05-17 17:00 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  var starRateContainer = booksContainer.getElementsByClassName("star-rating-container")[i];
не совсем поняла, что ты имел ввиду и как лучше сделать =(. Как я могу отрендерить сразу с рейтингом? я же далее и определяю логику, чтобы отрендерить звезды.

2019-05-17 17:02 UTC, Indigoinspn commented on src/ex13_library/main.js
> +document.body.style.overflow = "hidden";
Могу я как общий контейнер использовать body?  У меня он в принципе и так 100vh.  Убрала из js первую строку (document.body.style.overflow = "hidden";)

2019-05-17 18:54 UTC, eugrdn commented on src/ex13_library/main.js
> +document.body.style.overflow = "hidden";
да, ок

2019-05-17 19:06 UTC, eugrdn commented on src/ex13_library/main.js
> +  var starRateContainer = booksContainer.getElementsByClassName("star-rating-container")[i];
> booksContainer.innerHTML +=

добавила книгу в dom

> var starRateContainer =

получила рейтинг той же книги

ты же можешь

> booksContainer.innerHTML +=

перенести в самый конец функции и просто вставить рассчитанный рейтинг сюда

>  + item.id + "\" >___________ \</div>

2019-05-18 16:59 UTC, Indigoinspn commented on src/ex13_library/main.js
> +dataBooks.forEach(renderBooks);
поправила

2019-05-18 17:03 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  var starRateContainer = booksContainer.getElementsByClassName("star-rating-container")[i];
Попробовала так сделать, не получилось. Броузер сам добавляет закрывающий тег для контейнера звезд  (star-rating-container) и звезды оказываются за его пределами. Поэтому и приходится указать "var starRateContainer".

2019-05-18 17:04 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  var wholeFilledStars = Math.round(Math.floor(starRate));
Вынесла

2019-05-18 17:04 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  if (start === 0 & finish === 0) { // if bookRating 0 and initial filledStarIndex = selectedStarIndex = 0 (=index of fist star half)
Поправила

2019-05-18 17:07 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  for (var k = 0; k < stars.length; k++) {
Попробовала, не получилось. Мне нужно чтобы вернулся индекс выбранной звезды, а forEach возвращает undefined. Вернулась к обычному перебору(

2019-05-18 17:09 UTC, Indigoinspn commented on src/ex13_library/main.js
> +var bookId,
Перенесла внутрь функции и столкнулась с проблемой передачи значению в другие функции.
Передаю в ф-ю displayUserStarRatingChoice  и в ней хочу переприсвоить значения, а линтер ругается. Всю голову сломала(, как быть?

2019-05-18 17:11 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  getBookRating (bookIndex); // get rating from dataBooks array and save to filledStarIndex
Сохраняю теперь в  filledStarIndex = getBookRating(bookIndex); Еще проблема, ф-я findIndexOfSelectedStar(stars) должна что-то возвращать в конце, а мне нужно чтобы возвращала только нужное значение(. Что в общем return сделать?

2019-05-18 17:12 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  findIndexOfSelectedStar(target,bookIndex);
Разбила на несколько, но появились другие проблемы ( скрыла от линтера, чтобы с тобой посоветоваться)

2019-05-22 06:54 UTC, eugrdn commented on src/ex13_library/main.js
> +  if (dataBooks[bookIndex].rating === 0) rating = 0;
давай здесь нормальным синтаксисом
`if () {

} else {

}`

2019-05-22 06:55 UTC, eugrdn commented on src/ex13_library/main.js
> +  var starRateContainer = booksContainer.getElementsByClassName("star-rating-container")[i];
здесь это делать не нужно, все что у тебя ниже добавляется в starRateContainer.innerHTML просто записывай в одну переменную, а потом вставь ее строкой между тегами div, где формируется booksContainer, в star-rating-container

2019-05-22 06:56 UTC, eugrdn commented on src/ex13_library/main.js
> +  for (var k = 0; k < stars.length; k++) {
используй метод `.find`

2019-05-22 11:02 UTC, eugrdn commented on src/ex13_library/main.js
> +      bookRatingValue = 0.5;    // eslint-disable-line
это значение нигде не используется и ниже тоже в условиях

2019-05-22 11:03 UTC, eugrdn commented on src/ex13_library/main.js
> +  return bookRatingValue;
обычно set-методы не возвращают значений

2019-05-22 11:03 UTC, eugrdn commented on src/ex13_library/main.js
> +  getBookRating(bookIndex);
зачем здесь вызывается?

2019-05-23 14:04 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  var starRateContainer = booksContainer.getElementsByClassName("star-rating-container")[i];
Сделала

2019-05-23 14:04 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  if (dataBooks[bookIndex].rating === 0) rating = 0;
Сделала

2019-05-23 14:06 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  for (var k = 0; k < stars.length; k++) {
Использовала findIndex().

2019-05-23 14:09 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  var starRateContainer = booksContainer.getElementsByClassName("star-rating-container")[i];
Рассчитанный рейтинг сохранила в переменную и  потом добавила в booksContainer.innerHTML

2019-05-23 14:14 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  getBookRating(bookIndex);
Убрала getBookRating(bookIndex), без него все работает)

2019-05-23 14:32 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  getBookRating (bookIndex); // get rating from dataBooks array and save to filledStarIndex
Поправила

2019-05-26 08:28 UTC, Indigoinspn commented on src/ex13_library/main.js
> +  return bookRatingValue;
Поправила

2019-05-26 08:39 UTC, Indigoinspn commented on src/ex13_library/main.js
> +      bookRatingValue = 0.5;    // eslint-disable-line
Поправила

2019-05-27 20:41 UTC, merged